import type { PhotographerProfile, Review, User, Booking, Message, Job, JobApplication } from "./types"

export const mockPhotographers: (PhotographerProfile & { user: User })[] = [
  {
    id: "1",
    userId: "p1",
    bio: "Award-winning wedding photographer with 10+ years of experience capturing love stories. Specializing in candid moments and emotional storytelling.",
    specialties: ["Events", "Weddings"],
    location: "New York, NY",
    hourlyRate: 250,
    rating: 4.9,
    reviewCount: 127,
    portfolioImages: [
      "/wedding-event-photography.png",
      "/wedding-ceremony-outdoor.jpg",
      "/wedding-reception-dance.jpg",
    ],
    availability: true,
    user: {
      id: "p1",
      email: "sarah@example.com",
      name: "Sarah Johnson",
      role: "photographer",
      avatar: "/professional-woman-photographer.jpg",
      createdAt: new Date("2023-01-15"),
    },
  },
  {
    id: "2",
    userId: "p2",
    bio: "Professional portrait photographer focused on bringing out the best in every subject. Natural light specialist with a modern, editorial style.",
    specialties: ["Portraits", "Headshots"],
    location: "Los Angeles, CA",
    hourlyRate: 180,
    rating: 4.8,
    reviewCount: 89,
    portfolioImages: [
      "/professional-portrait.png",
      "/professional-headshot-studio.jpg",
      "/outdoor-portrait-natural-light.jpg",
    ],
    availability: true,
    user: {
      id: "p2",
      email: "michael@example.com",
      name: "Michael Chen",
      role: "photographer",
      avatar: "/asian-male-photographer.png",
      createdAt: new Date("2023-03-20"),
    },
  },
  {
    id: "3",
    userId: "p3",
    bio: "E-commerce and product photography expert. I help brands showcase their products with stunning, high-converting images.",
    specialties: ["Products", "Commercial"],
    location: "San Francisco, CA",
    hourlyRate: 200,
    rating: 5.0,
    reviewCount: 64,
    portfolioImages: [
      "/product-photography-studio.png",
      "/product-photography-white-background.jpg",
      "/lifestyle-product-photography.png",
    ],
    availability: true,
    user: {
      id: "p3",
      email: "emma@example.com",
      name: "Emma Rodriguez",
      role: "photographer",
      avatar: "/latina-woman-photographer.jpg",
      createdAt: new Date("2023-02-10"),
    },
  },
  {
    id: "4",
    userId: "p4",
    bio: "Real estate photography specialist helping agents sell properties faster with professional imagery and virtual tours.",
    specialties: ["Real Estate", "Architecture"],
    location: "Miami, FL",
    hourlyRate: 150,
    rating: 4.7,
    reviewCount: 112,
    portfolioImages: [
      "/real-estate-interior-photography.jpg",
      "/luxury-home-exterior.png",
      "/modern-kitchen-real-estate.jpg",
    ],
    availability: true,
    user: {
      id: "p4",
      email: "david@example.com",
      name: "David Martinez",
      role: "photographer",
      avatar: "/male-photographer.png",
      createdAt: new Date("2023-04-05"),
    },
  },
  {
    id: "5",
    userId: "p5",
    bio: "Fashion and editorial photographer with a bold, creative vision. Published in major magazines and worked with top brands.",
    specialties: ["Fashion", "Editorial"],
    location: "New York, NY",
    hourlyRate: 300,
    rating: 4.9,
    reviewCount: 78,
    portfolioImages: [
      "/fashion-photography-studio.jpg",
      "/editorial-fashion-outdoor.jpg",
      "/fashion-model-portrait.png",
    ],
    availability: false,
    user: {
      id: "p5",
      email: "alex@example.com",
      name: "Alex Thompson",
      role: "photographer",
      avatar: "/photographer-with-professional-camera.jpg",
      createdAt: new Date("2023-01-28"),
    },
  },
  {
    id: "6",
    userId: "p6",
    bio: "Family and lifestyle photographer capturing authentic moments. Specializing in outdoor sessions and natural interactions.",
    specialties: ["Family", "Lifestyle"],
    location: "Austin, TX",
    hourlyRate: 175,
    rating: 4.8,
    reviewCount: 95,
    portfolioImages: [
      "/family-photography-outdoor-park.jpg",
      "/children-playing-candid.jpg",
      "/family-portrait-sunset.jpg",
    ],
    availability: true,
    user: {
      id: "p6",
      email: "jessica@example.com",
      name: "Jessica Williams",
      role: "photographer",
      avatar: "/woman-photographer-smiling.jpg",
      createdAt: new Date("2023-05-12"),
    },
  },
]

export const mockReviews: Review[] = [
  {
    id: "r1",
    bookingId: "b1",
    clientId: "c1",
    photographerId: "p1",
    rating: 5,
    comment:
      "Sarah was absolutely amazing! She captured our wedding day perfectly and made us feel so comfortable. The photos are stunning and we'll treasure them forever.",
    createdAt: new Date("2024-09-15"),
  },
  {
    id: "r2",
    bookingId: "b2",
    clientId: "c2",
    photographerId: "p1",
    rating: 5,
    comment: "Professional, creative, and a joy to work with. Highly recommend for any event!",
    createdAt: new Date("2024-08-22"),
  },
  {
    id: "r3",
    bookingId: "b3",
    clientId: "c3",
    photographerId: "p1",
    rating: 4,
    comment: "Great photographer with excellent attention to detail. Very happy with the results.",
    createdAt: new Date("2024-07-10"),
  },
]

export const mockBookings: Booking[] = [
  {
    id: "b1",
    clientId: "c1",
    photographerId: "p1",
    date: new Date("2025-01-15T14:00:00"),
    duration: 4,
    location: "Central Park, New York, NY",
    type: "Wedding",
    status: "confirmed",
    totalPrice: 1000,
    notes: "Outdoor ceremony, need to capture candid moments",
  },
  {
    id: "b2",
    clientId: "c2",
    photographerId: "p1",
    date: new Date("2025-01-20T10:00:00"),
    duration: 2,
    location: "Brooklyn Studio, NY",
    type: "Portrait",
    status: "pending",
    totalPrice: 500,
    notes: "Professional headshots for LinkedIn",
  },
  {
    id: "b3",
    clientId: "c3",
    photographerId: "p1",
    date: new Date("2024-12-10T16:00:00"),
    duration: 3,
    location: "Manhattan Event Hall, NY",
    type: "Event",
    status: "completed",
    totalPrice: 750,
  },
  {
    id: "b4",
    clientId: "c4",
    photographerId: "p1",
    date: new Date("2024-11-25T13:00:00"),
    duration: 5,
    location: "Plaza Hotel, New York, NY",
    type: "Wedding",
    status: "completed",
    totalPrice: 1250,
  },
]

export const mockMessages: Message[] = [
  {
    id: "m1",
    senderId: "c1",
    receiverId: "p1",
    content: "Hi! I'm interested in booking you for my wedding. Are you available on June 15th?",
    createdAt: new Date("2025-01-05T10:30:00"),
    read: true,
  },
  {
    id: "m2",
    senderId: "p1",
    receiverId: "c1",
    content:
      "Hello! Yes, I'm available on that date. I'd love to discuss your wedding photography needs. What time were you thinking?",
    createdAt: new Date("2025-01-05T11:15:00"),
    read: true,
  },
  {
    id: "m3",
    senderId: "c1",
    receiverId: "p1",
    content: "Great! The ceremony starts at 2 PM. We'd need coverage from 1 PM to 8 PM. Can you handle that?",
    createdAt: new Date("2025-01-05T11:45:00"),
    read: true,
  },
  {
    id: "m4",
    senderId: "p1",
    receiverId: "c1",
    content:
      "7 hours of coverage is perfect for a wedding. I'll capture everything from getting ready to the reception. My rate is $250/hour. Would you like to proceed with a booking?",
    createdAt: new Date("2025-01-05T12:00:00"),
    read: false,
  },
]

export const mockJobs: Job[] = [
  {
    id: "j1",
    clientId: "c1",
    title: "Summer Wedding in Central Park",
    description: "Looking for a photographer for a 4-hour outdoor wedding ceremony. Candid shots are a priority.",
    location: "Central Park, NY",
    category: "Weddings",
    date: new Date("2025-06-15T14:00:00"),
    durationHours: 4,
    budget: 1000,
    status: "open",
    createdAt: new Date("2025-03-20T10:00:00"),
  },
  {
    id: "j2",
    clientId: "c2",
    title: "Startup Headshots",
    description: "Need professional headshots for our team of 10 people. Fast turnaround needed.",
    location: "Brooklyn, NY",
    category: "Headshots",
    date: new Date("2025-04-10T10:00:00"),
    durationHours: 3,
    budget: 600,
    status: "open",
    createdAt: new Date("2025-03-22T09:30:00"),
  },
]

